const web3Actions = {
  NEW_STATE: 'NEW_STATE',
  SET_ACCOUNT: 'SET_ACCOUNT',
  REQUEST_DEPLOY_EXAMPLECOIN_CONTRACT: 'REQUEST_DEPLOY_EXAMPLECOIN_CONTRACT',
  SUCCESS_DEPLOY_EXAMPLECOIN_CONTRACT: 'SUCCESS_DEPLOY_EXAMPLECOIN_CONTRACT',
  ERROR_DEPLOY_EXAMPLECOIN_CONTRACT: 'ERROR_DEPLOY_EXAMPLECOIN_CONTRACT',
  SET_BALANCE: 'SET_BALANCE',
  SET_BALANCE_IN_ETHER: 'SET_BALANCE_IN_ETHER'
};

module.exports = web3Actions;
